os:
  - linux
dist: focal

language: node_js
node_js:
  - node
  - lts/*

services:
  - docker

stages:
  - test
  - name: release
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: release
      install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t file-server .
        - |
          if [ -z $TRAVIS_TAG ]
          then
            docker tag file-server $DOCKER_NAMESPACE/file-server:master
            docker push $DOCKER_NAMESPACE/file-server:master
          else
            docker tag file-server $DOCKER_NAMESPACE/file-server:latest
            docker tag file-server $DOCKER_NAMESPACE/file-server:$TRAVIS_TAG
            docker push $DOCKER_NAMESPACE/file-server:latest
            docker push $DOCKER_NAMESPACE/file-server:$TRAVIS_TAG
          fi
